config/routes.rb
Rails.application.routes.draw do
 

  resources :users do 
    resources :rooms, only: [:index, :new, :create, :destroy]
  end
  # resources :categories
  # resources :posts
  resources :rooms do 
    resources :messages
  end
  

  resources :users do 
    resources :profiles, only: [:edit, :new, :create, :update]
  end

  resources :users do 
    resources :posts, only: [:new, :edit, :destroy]
  end

  resources :posts, only: [:index, :create, :update]
  resources :profiles, only: [:index]
  # get '/search', to: "profiles#index"

  get 'users/:id/profile', to: 'profiles#view', as: 'view_profile'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'
  get '/auth/facebook/callback', to: 'sessions#omniauth'

  # get 'sign_up', action: :new, controller: 'registrations'
  
  get 'signup', to: "registrations#new" 
  post 'signup', to: "registrations#create" 
  get 'login', to: "sessions#new" 
  post 'login', to: "sessions#create" 
  get 'logout', to: 'sessions#destroy'
  get 'password/edit', to: 'passwords#edit', as: 'edit_password'
  patch 'password/edit', to: 'passwords#update'
  get '/cancel', to: 'users#destroy', as: 'cancel'

end

app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user

    validates :username, presence: true, uniqueness: { case_sensitive: false }
    validates :avatar, presence: true
    validates :bio, presence: true
    validates :cover, presence: true

    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

    has_attached_file :cover, styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/

    scope :search_by_username, -> (search_text) {where("lower(username) LIKE :search", search: "%#{search_text}%")}


end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :require_set_profile!, only: [:edit, :update]
    before_action :correct_user_profile, only: [:edit, :update]
    before_action :account_deleted!, only: [:view]

    def index
        @profiles = Profile.all
        if !params[:search].blank? 
            @profiles = Profile.search_by_username(params[:search])
        end
    end

    def new 
        @user = @current_user
        @profile = @user.build_profile
    end

    def create 
        @profile = @current_user.build_profile(profile_params)
        if @profile.save 
            redirect_to  view_profile_path(@current_user), notice: "Profile successfully created!"
        else
            render :new
            flash[:notice] = "Unsuccessful!"
        end
    end

    def view
        @user = User.find(params[:id])
        if @user == @current_user
            @user = @current_user  
            @profile = @current_user.profile
            @posts = @current_user.posts
        else
            @profile = @user.profile
            @posts = @user.posts
        end
    end


    def edit 
        @user = @current_user
        @profile = @current_user.profile
    end

    def update 
        @profile = @current_user.profile
        if @profile.update(profile_params)
            redirect_to view_profile_path(@current_user), notice: "Profile successfully updated!"
        else
            render :edit 
            flash[:notice] = "Unsuccessful!"
        end
    end

    private 
    def profile_params 
        params.require(:profile).permit(:username, :avatar, :user_id, :bio, :cover, :search)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper

    def uniq_category_name(p)
        p.map do |post|
            post.categories
        end.flatten.uniq.map {|c| c.name}.join(", ")
    end

end

app/views/profiles/_form.html.erb
<%= form_for [@user, @profile] do |f| %>

    <% if @profile.errors.any? %>
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li> 
        <% end %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
    <% end %>
    <br>

    <div class= "reg-form-profile">
        <div class="field form-group">
            <%= f.label "User Name:", class: "form-label" %>
            <%= f.text_field :username, class: "form-control" %>
        </div><br>

        <div class="field form-group">
            <%= f.label "Write about yourself:", class: "form-label" %>
            <%= f.text_area :bio, :cols => 20, :rows => 5, class: "form-control" %>
        </div><br>

        <div class="field form-group">
            <%= f.label "Choose Profile Picture:", class: "form-label" %>
        </div>
        <div class="input-group">
            <%= f.file_field :avatar, class: "form-control", onchange: "showPreview(event)"%>
        </div>
        <div class="preview">
            <img class="image-preview">
        </div><br><br>

        <div class="field form-group">
            <%= f.label "Choose Cover Picture:", class: "form-label" %>
        </div>
        <div class="input-group">
            <%= f.file_field :cover, class: "form-control ", onchange: "showCoverPreview(event)"%>
        </div>
        <div class="preview">
            <img class="cover-image-preview">
        </div>
        <br><br>

        <div class="actions">
            <%= f.submit "Save", class: "btn btn-success" %>
        </div><br>
    </div><br>


        <%= f.hidden_field :user_id, value: @current_user.id%>
<% end %>

app/views/profiles/_profile.html.erb
<div class="content">
    <div class="user_profile_cap">

        <div class="user_profile_cover", style = "background-image: url(<%= profile.cover.url%>);"></div>

        <div class="user_profile_headline">
            <%= image_tag profile.avatar.url(:medium) %> 

            <h2><%= profile.username %></h2>
            <span><%= profile.bio %></span><br>
            <span><i><small><%= current_city %>, <%= current_country %></small></i></span><br>
            <strong>Interested in:  
                <i style= "color:red;">       
                    <%= uniq_category_name profile.user.posts %>
                </i>
            </strong>
        </div>
    </div><br>
    
    <% if profile.user == current_user %>
        <%= link_to 'Edit Profile', edit_user_profile_path(user.id, profile.id), class: "btn btn-primary" %> 
        <%= link_to 'Edit Password', edit_password_path, class: "btn btn-primary" %> 
        <%= link_to 'Back', root_path, class: "btn btn-primary" %>
        <div class="card">
            <h5 class="card-header">Unhappy?? Cancel your account here</h5>
            <div class="card-body">
                <%= link_to 'Cancel Account', user_path, class: 'btn btn-outline-danger btn-sm', data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
            </div>
        </div><br>
    <% else %>
        <%= link_to 'Back', root_path, class: "btn btn-primary", style: 'float:right;' %>
        <%= button_to 'Team UP', rooms_path(sender_id: current_user.id, recipient_id: params["id"]), method: :post, class: "btn btn-danger" %>
    <% end %>
    <br><br>
</div>

app/views/profiles/_searched.html.erb
<%# <h4>All Users</h4> %>
<% profiles.each do |profile| %>
    <%= link_to_image(profile.avatar.url, "in-posts-avatar", view_profile_path(id: profile.user.id)) %>
    <strong><%= link_to profile.username, view_profile_path(id: profile.user.id), class: "friends-name" %></strong><br><br>
<% end %>

app/views/profiles/_searchform.html.erb
<div class="search-container">
    <%= form_tag(profiles_path, method: :get) do %>
    <%= search_field_tag :search, params[:search], placeholder: "Search Mates...", class: 'search-form-input' %>
    <button type="submit" class="btn btn-warning btn-sm">Search</button>
    <% end %>
</div>

app/views/profiles/edit.html.erb
<div class="content">
    <br>
    <h3>Edit Profile</h3>
    <%= render 'form' %>
</div>
<%= render partial: 'profile', locals: {profile: @profile, user: @user, current_country: @current_country, current_city: @current_city, posts: @user.posts} %>

app/views/profiles/index.html.erb
<div class="content-posts">
    <% if params[:search] %>
         <h4>Showing Results for: <span style="color: darkblue"><%= params[:search] %></span></h4>
    <% end %>
    <% @profiles.each do |profile| %>
        <%= render partial: 'posts/posts', locals: {posts: profile.user.posts, current_city: @current_city, current_country: @current_country} %>
    <% end %>
</div>

app/views/profiles/new.html.erb
<div class="content">
    <br>
    <h3>Set Up Profile</h3>
    <%= render 'form', locals: {profile: @profile, user: @user} %>
</div>

app/views/profiles/show.html.erb
<%# <%= render partial: 'profile', locals: {profile: @profile, user: @user, current_country: @current_country, current_city: @current_city, posts: @user.posts} %> %>

app/views/profiles/view.html.erb
<%= render partial: 'profile', locals: {profile: @profile, user: @user, current_country: @current_country, current_city: @current_city, room: @profile.user.rooms.new} %>

<%= render template: 'posts/index' %>