config/routes.rb
Rails.application.routes.draw do
 

  resources :users do 
    resources :rooms, only: [:index, :new, :create, :destroy]
  end
  # resources :categories
  # resources :posts
  resources :rooms do 
    resources :messages
  end
  

  resources :users do 
    resources :profiles, only: [:edit, :new, :create, :update]
  end

  resources :users do 
    resources :posts, only: [:new, :edit, :destroy]
  end

  resources :posts, only: [:index, :create, :update]
  resources :profiles, only: [:index]
  # get '/search', to: "profiles#index"

  get 'users/:id/profile', to: 'profiles#view', as: 'view_profile'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'
  get '/auth/facebook/callback', to: 'sessions#omniauth'

  # get 'sign_up', action: :new, controller: 'registrations'
  
  get 'signup', to: "registrations#new" 
  post 'signup', to: "registrations#create" 
  get 'login', to: "sessions#new" 
  post 'login', to: "sessions#create" 
  get 'logout', to: 'sessions#destroy'
  get 'password/edit', to: 'passwords#edit', as: 'edit_password'
  patch 'password/edit', to: 'passwords#update'
  get '/cancel', to: 'users#destroy', as: 'cancel'

end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :post_categories
    has_many :categories, through: :post_categories, dependent: :destroy

    validates :caption, presence: true
    
    validates :post_file, presence: true
    validates :post_file, file_size: { less_than_or_equal_to: 200.megabytes, message: "Please Check File Size" }

    default_scope {order(updated_at: :desc)}

    accepts_nested_attributes_for :categories

    has_one_attached :post_file
    

    def categories_attributes=(category_attributes)
        category_attributes.values.each do |category_attr|
          if category_attr["name"].present? 
            category = Category.find_or_create_by(category_attr)
            self.categories << category
          end
        end
    end

    def self.by_category(category_id)
      if category_id
        self.includes(:categories).where(categories: { id: category_id})
      end
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :require_set_profile! 
    
    def index 
        @posts = Post.all
        
        if !params[:category].blank?
            @posts = Post.by_category(params[:category])
        else
            @posts = Post.all
        end


    end

    def new 
        @post = Post.new     
    end 

    def create 
        # raise params.inspect
        @post = Post.create(post_params)
 
        if @post.save 
            redirect_to root_path, notice: "Post Uploaded!"
        else
            render :new
            flash[:notice] = "Post creation is unsuccessful!"
        end
    end

    def show 
        @posts = @current_user.posts
    end

    def edit 
        @post = @current_user.posts.find(params[:id])
    end

    def update 
        @post = @current_user.posts.find(params[:id])
        if @post.update(post_params)
            redirect_to root_path, notice: "Post is successfully updated!"

        else
            render :edit
            flash[:notice] = "Post update is unsuccessful!"
        end
    end
    
    def destroy
        @post = @current_user.posts.find(params[:id])
        @post.destroy 
        redirect_to root_path, notice: "Post Successfully Destroyed!"
    end

    private 

    def post_params 
        params.require(:post).permit(:caption, :post_file, :user_id, category_ids:[], categories_attributes: [:name])
    end

end

app/helpers/posts_helper.rb
module PostsHelper
    def last_updated(post)
        post.updated_at.strftime("Last updated %A, %b %e, at %l:%M %p")
    end

    def all_posts
        Post.all
    end
end

app/views/posts/_form.html.erb
<% if post.invalid? %>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <li><%= post.errors.full_messages[1] %></li> 
        <li><%= post.errors.full_messages[2] %></li> 
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>
<div class="post-form">
    <h3>Create a Post</h3>
    <br>
    <%= form_for post do |f| %>
        <%= f.text_area :caption, placeholder: "What's on your mind?", :cols => 30, :rows => 3, class: "caption-box"  %>
        <br><br>

        <%= f.label "Choose an Image or a Video to Upload:" %>
        <%= f.file_field :post_file, class: "form-control", onchange: "showPreview(event)" %>
        <div class="preview">
            <img class="image-preview">
            <video class="video-preview" controls></video>
        </div>
        <%= f.label "Select Games related to your post:" %>
        <div class= "checkboxes">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name %>
        </div><br>

        <button class="toggler btn btn-warning btn-sm", onclick="handleAddCategoryToggler(event)">Add Games</button>
        <br><br>
        
        <div class="category-input">
            <%= f.fields_for :categories, post.categories.build do |categories_fields| %>
                <%= categories_fields.label :name, "Enter Game Name: " %>
                <%= categories_fields.text_field :name %>
            <% end %>
        </div>
        <br>

        <%= f.hidden_field :user_id, value: @current_user.id%>

        <div class="actions">
            <%= f.submit "Save", class: "btn btn-success" %>
        </div><br>
    <% end %>
    <div class="close-post-form">
        <button class= "btn btn-danger btn-sm" onclick="handlePostFormClose()">Close</button>
    </div>
</div>

app/views/posts/_index.html.erb
<% posts.each do |post| %>
    <div class="home-posts">
        <%= link_to_image(post.user.profile.avatar.url, "in-posts-avatar", view_profile_path(id: post.user.id)) %>
        <%= link_to post.user.profile.username, view_profile_path(id: post.user.id), class: "posts-username"  %><%=  %><br>
        <span><i><small>📍<%= current_city %>, <%= current_country %></small></i></span><br><br>
        <%= post.caption %>
        <br>

        <div class="post-image-div", style = "background-image: url(<%= post.image.url%>);"></div><br>

        <% if post.user == current_user  %> 
            <%= link_to "Edit Post", edit_user_post_path(user_id: post.user_id, id: post.id), class: "btn btn-primary btn-sm" %>
            <%= link_to "Delete Post", user_post_path(post.user, post), class: "btn btn-danger btn-sm", style: "float: right;", data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure?"
              }  %>
        <% end %>
    </div>
<% end %>


 

app/views/posts/_posts.html.erb
<% posts.each do |post| %>
    <div class="home-posts">
        <%= link_to_image(post.user.profile.avatar.url, "in-posts-avatar", view_profile_path(id: post.user.id)) %>
        <%= link_to post.user.profile.username, view_profile_path(id: post.user.id), class: "posts-username"  %><%=  %>
        <span class="time-ago"><%= time_ago_in_words(post.updated_at) %> ago</span><br>
        <span><i><small>📍<%= current_city %>, <%= current_country %></small></i></span><br><br>
        <%= post.caption %>
        <br>

        <% if post.post_file.attached? %>
            <% if post.post_file.content_type.include?("image") %>
                <div class="post-image-div", style = "background-image: url(<%= url_for(post.post_file) %>);"></div>
            <% else %>
                <%= video_tag url_for(post.post_file), controls: true, style: "height: 350px; width: 480px;" %>
            <% end %>
        <% end %>
        <br>
    
        <% if post.user == current_user  %> 
            <%= link_to "Edit Post", edit_user_post_path(user_id: post.user_id, id: post.id), class: "btn btn-primary btn-sm" %>
            <%= link_to "Delete Post", user_post_path(post.user, post), class: "btn btn-danger btn-sm", style: "float: right;", data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure?"
            }  %>
        <% end %>
    </div>
<% end %>

app/views/posts/edit.html.erb
<div class="content">
    <div class="edit-post-form">
        <h3>Edit Post</h3>
            <%= render partial: 'form', locals: {post: @post} %>
    </div>
</div>

app/views/posts/index.html.erb
<div class="content-posts">
    <% if params[:category] %>
        <h4>Showing Results for: <span style="color: darkblue"><%= searched_category %></span></h4>
    <% end %>
    <br> 

    <%= render partial: 'posts/posts', locals: {posts: @posts, current_city: @current_city, current_country: @current_country } %>
</div>

app/views/posts/new.html.erb
<div class="content">
    <h3>Create Post</h3>
    <%# <%= form_for @post, url: user_posts_path(user_id: current_user.id) do |f| %> %>
        <%= render partial: 'form', locals: {post: @post} %>
    <%# <% end %> %>
</div>