config/routes.rb
Rails.application.routes.draw do
 

  resources :users do 
    resources :rooms, only: [:index, :new, :create, :destroy]
  end
  # resources :categories
  # resources :posts
  resources :rooms do 
    resources :messages
  end
  

  resources :users do 
    resources :profiles, only: [:edit, :new, :create, :update]
  end

  resources :users do 
    resources :posts, only: [:new, :edit, :destroy]
  end

  resources :posts, only: [:index, :create, :update]
  resources :profiles, only: [:index]
  # get '/search', to: "profiles#index"

  get 'users/:id/profile', to: 'profiles#view', as: 'view_profile'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'
  get '/auth/facebook/callback', to: 'sessions#omniauth'

  # get 'sign_up', action: :new, controller: 'registrations'
  
  get 'signup', to: "registrations#new" 
  post 'signup', to: "registrations#create" 
  get 'login', to: "sessions#new" 
  post 'login', to: "sessions#create" 
  get 'logout', to: 'sessions#destroy'
  get 'password/edit', to: 'passwords#edit', as: 'edit_password'
  patch 'password/edit', to: 'passwords#update'
  get '/cancel', to: 'users#destroy', as: 'cancel'

end

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show content-alert" role="alert">
  <%= notice%> 
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>     

app/views/layouts/_nav.html.erb
<!-- The sidebar -->
<div class="sidebar">
  <% if current_user.profile.nil? %>
    <%= link_to "Create a Profile", new_user_profile_path(user_id: user), class: "#{active_class(new_user_profile_path(user_id: user))}" %>
  <% else %>
    <%= link_to_image("#{user.profile.avatar.url}", "profile-pic", view_profile_path(id: user), class: "#{active_class(view_profile_path(id: user))}") %>
  <% end %>
  <%= link_to "Home", root_path, class: "#{active_class(root_path) }" %>
  <%= link_to "Chat", rooms_path %>
  <%= link_to "Log Out", logout_path , method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/layouts/_topnav.html.erb
<div class="topnav">
  <div class="logo-head-nav">
    <%= image_tag 'logo.png', class: 'logo navbar-brand' %>
    <div class="welcome"> Welcome, <%= user.first_name  %></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Play Mates</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags  %>
  </head>

  <body class = "body">
    
    <% if @current_user %>
      <%= render partial: 'layouts/topnav', locals: {user: current_user} %>
      <%= render partial: 'layouts/nav', locals: {user: current_user }%> 
    <div class="right-sidebar">
      <%= render partial: 'profiles/searchform' %>
        <br>
      <%= render partial: 'profiles/searched', locals: {profiles: all_profiles} %>
    </div>  
    <% else %>
      <div class="logo-head">
        <%= image_tag 'logo.png', class: 'logo' %>
      </div>
    <% end %>

    <div class = "container">
    <br><br>
      <% if notice  %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>
</html>